####
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Daniel Temesgen
description: A Software Engineer interested in design, backend and web development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_repo: danieltemesgen.github.io # the GitHub repo name for your project
github_username: danieltemesgen
github: [metadata]

# Optional social link, you can choose from the following options:
# twitter (default), instagram, medium, or dribbble

social_link: linkedin
linkedin_username: dtemesgen

social_link: goodreads
goodreads_username: danieltemesgen

social_email: Daniel.Temesgen@gmail.com

cv_location: /assets/pdfs/CV.pdf
# Set theme color here
# Choose from: black (default), blue, gray, magenta, orange, red, white, and yellow.
theme_color: white

# Build settings
markdown: kramdown

#theme: minima
remote_theme: danieltemesgen/swiss #this is a fork of the broccolini swiss repo, with some customisation.
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-sitemap

# This makes the link for posts make sense
#permalink: /words/:title
